name: osur2017
channels:
  - sympy
  - conda-forge
  - damianavila82
  - defaults
dependencies:
  - python>=3.5
  - setuptools
  - numpy
  - numexpr
  - matplotlib
  - scipy
  - cython
  - sympy
  - numba
  - seaborn
  - h5py 
  - lorem 
  - joblib 
  - fortran-magic 
  - cython 
  - line_profiler 
  - memory_profiler
  - numba
  - progressbar2
  - ujson
  - ipywidgets
  - pip
  - gcc
  - pip:
    - loky
    - nbopen
    - pythran
    - py-heat-magic
